#!/usr/bin/env node
// Rebuilds the Roadmap epic (#22) from GitHub: its sub-issues, their "Blocked by" links, labels and state.
//   npm run roadmap           → print the generated Markdown
//   npm run roadmap -- --write → replace the generated part of the epic's body
// Needs the GitHub CLI (`gh auth login`).
import { execFileSync } from 'node:child_process';

const REPO = 'euhoro/YmarqApp';
const EPIC = 22;
const START = '<!-- roadmap:start -->';
const END = '<!-- roadmap:end -->';

const api = (path) =>
  JSON.parse(
    execFileSync('gh', ['api', '--paginate', '--slurp', path], { encoding: 'utf8' }),
  ).flat();

const issues = api(`repos/${REPO}/issues/${EPIC}/sub_issues?per_page=100`).map((issue) => ({
  number: issue.number,
  title: issue.title,
  closed: issue.state === 'closed',
  dropped: issue.state_reason === 'not_planned',
  labels: issue.labels.map((label) => label.name),
  blockedBy: api(`repos/${REPO}/issues/${issue.number}/dependencies/blocked_by?per_page=100`).map(
    (dep) => ({ number: dep.number, closed: dep.state === 'closed' }),
  ),
}));

const has = (issue, label) => issue.labels.includes(label);
const openBlockers = (issue) => issue.blockedBy.filter((dep) => !dep.closed);

function group(issue) {
  if (issue.dropped) return 'dropped';
  if (issue.closed) return 'done';
  if (has(issue, 'deferred')) return 'later';
  if (has(issue, 'needs-decision')) return 'decision';
  if (openBlockers(issue).length > 0) return 'blocked';
  return has(issue, 'agent-ready') ? 'ready' : 'pairing';
}

const label = (issue) => `#${issue.number} ${issue.title}`.replace(/"/g, "'").slice(0, 60);

const graph = ['```mermaid', 'flowchart LR'];
for (const issue of issues) graph.push(`  n${issue.number}["${label(issue)}"]`);
for (const issue of issues) {
  for (const dep of issue.blockedBy) {
    if (issues.some((other) => other.number === dep.number)) {
      graph.push(`  n${dep.number} --> n${issue.number}`);
    }
  }
}
graph.push(
  '  classDef done fill:#ffffff,stroke:#0e8a16,stroke-dasharray:4 2,color:#777',
  '  classDef ready fill:#dff5e3,stroke:#0e8a16,color:#000',
  '  classDef pairing fill:#dbe9fb,stroke:#1d76db,color:#000',
  '  classDef blocked fill:#fde2e1,stroke:#b60205,color:#000',
  '  classDef decision fill:#ffe9d6,stroke:#d93f0b,color:#000',
  '  classDef later fill:#eeeeee,stroke:#999,color:#555',
  '  classDef dropped fill:#ffffff,stroke:#bbb,stroke-dasharray:2 2,color:#aaa',
);
for (const issue of issues) graph.push(`  class n${issue.number} ${group(issue)}`);
graph.push('```');

const sections = [
  ['ready', '🟢 Ready now (agent-ready, nothing blocking)'],
  ['pairing', '🔵 Ready now, needs a human (pairing)'],
  ['blocked', '🔴 Blocked'],
  ['decision', '🟠 Needs a decision'],
  ['later', '⚪ Later'],
  ['done', '✅ Done'],
  ['dropped', '🗑️ Closed without doing (replaced or not planned)'],
];
const lists = sections.flatMap(([key, heading]) => {
  const items = issues.filter((issue) => group(issue) === key);
  if (items.length === 0) return [];
  return [
    `### ${heading}`,
    ...items.map((issue) => {
      const waits = openBlockers(issue).map((dep) => `#${dep.number}`);
      const marks = `${has(issue, 'dod') ? ' ⭐' : ''}${has(issue, 'owner-task') ? ' 👤' : ''}`;
      return `- [${issue.closed ? 'x' : ' '}] #${issue.number}${marks}${waits.length ? ` (waits for ${waits.join(', ')})` : ''}`;
    }),
    '',
  ];
});

const generated = [
  START,
  `_Generated by \`npm run roadmap -- --write\` on ${new Date().toISOString().slice(0, 10)}. Edit issues, not this section._`,
  '',
  '## Dependency graph',
  'Arrow = "must be done before". Green = ready, blue = needs a human, red = blocked, orange = needs a decision, grey = later, dashed = done.',
  'In the lists: ⭐ = needed for the Definition of Done, 👤 = owner task.',
  '',
  ...graph,
  '',
  ...lists,
  END,
].join('\n');

if (!process.argv.includes('--write')) {
  console.log(generated);
} else {
  const current = JSON.parse(
    execFileSync('gh', ['api', `repos/${REPO}/issues/${EPIC}`], { encoding: 'utf8' }),
  ).body;
  const intro = current.includes(START)
    ? current.slice(0, current.indexOf(START))
    : `${current}\n\n`;
  const outro = current.includes(END) ? current.slice(current.indexOf(END) + END.length) : '';
  execFileSync('gh', ['issue', 'edit', String(EPIC), '--repo', REPO, '--body-file', '-'], {
    input: intro + generated + outro,
  });
  console.log(`Updated #${EPIC} (${issues.length} issues).`);
}
